### ISSUE TITLE
Does not respect existing flags

### ISSUE THREAD

**Issue by micdah** [oprogramador/deep-equal-in-any-order#60] opened 2021-08-10 12:21 UTC
Excellent plugin, but I just ran into an issue where it seems existing flags are not respected, I specifically use `.roughly` to perform comparisons with some tolerance as exact floating point comparison is errornous. 😄 

Looking into the source, I see that the issue probably is caused by the fact that a new `Assertion` object is made, without carrying over existing flags.

I have made a local version of your plugin which seems to work, and this is the code I'm working with:

```
        utils.addMethod(Assertion.prototype, 'equalInAnyOrder', function equalInAnyOrder(b, m) {
            utils.flag(this, 'object', sortDeep(utils.flag(this, 'object')))
            this.equal(sortDeep(b), m)
        });
```

I have opted to use `utils.flag` rather than relying on `this.__flags` as I assume `utils.flag()` is the official way for plugins to interact with flags, maybe they change behaviour for where flags are stored in the future.

Also changed so that no new `Assertion` is started, as far as I can tell there is no need - and this way flags are carried over automatically (_I could of course also just copy `this.__flags` into the new assertion object, but why make it more difficult than need be_).

Lastly I have removed the implicit `.deep`, more of a flavor thing for me, now that flags are preserved, I can do `.deep` when I want and not when I don't. 😄

**Comment by oprogramador** [comment] 2021-08-10 14:06
Thanks, @micdah for reporting this.

Could you post a test suite failing when it should be passing (or the opposite - passing when it should be failing)?

**Comment by nemo-5** [comment] 2021-11-24 11:28
Hi, we had a similar issue with when using `deep-equal-in-any-order` in combination with `chai-exclude`, an (almost) minimal failing example would e.g. be
```
import * as chai from 'chai';
import * as deepEqualInAnyOrder from 'deep-equal-in-any-order';
import chaiExclude from 'chai-exclude';

chai.use(deepEqualInAnyOrder).use(chaiExclude);

const expect = chai.expect;

it('should work but fails', function () {
  const test = [
    {
      hello: 'world',
      toBeExcluded: 1,
    },
    {
      hello: 'there',
      toBeExcluded: 1,
    },
  ];
  const expected = [
    {
      hello: 'there',
      toBeExcluded: 2,
    },
    {
      hello: 'world',
      toBeExcluded: 2,
    },
  ];

  expect(test).excludingEvery('toBeExcluded').to.deep.equalInAnyOrder(expected);
});
``` 
I also had experimented with the code for a little bit and had arrived at the following modification that worked for me (less concise as what @micdah proposed above though)
```
module.exports = (chai, utils) => {
  const { Assertion } = chai;
  utils.addMethod(Assertion.prototype, 'equalInAnyOrder', function equalInAnyOrder(b, m) {
    const a = this.__flags.object;
    const { negate, message } = this.__flags;

    const msg = m || message;

    const newAssertion = new Assertion(sortDeep(a), msg)
    utils.transferFlags(this, newAssertion, false);        // Added to preserve custom flags

    if (negate) {
      newAssertion.to.not.deep.equal(sortDeep(b));
    } else {
      newAssertion.to.deep.equal(sortDeep(b));
    }
  });
};
```

**Comment by oprogramador** [comment] 2021-11-24 15:06
Thanks @nemo-5

**Comment by nemo-5** [comment] 2021-11-24 18:19
@oprogramador Thank you for maintaining this plugin! :) 
Btw I just realized that I didn't spend a thought on the negate branch, I think with the transferred flags it could just be removed, e.g.
```
module.exports = (chai, utils) => {
  const { Assertion } = chai;
  utils.addMethod(Assertion.prototype, 'equalInAnyOrder', function equalInAnyOrder(b, m) {
    const a = this.__flags.object;
    const { message } = this.__flags;

    const msg = m || message;

    const newAssertion = new Assertion(sortDeep(a), msg)
    utils.transferFlags(this, newAssertion, false);        // Added to preserve custom flags
    newAssertion.to.deep.equal(sortDeep(b));
  });
};
```

**Comment by oprogramador** [comment] 2022-06-29 03:20
@micdah @nemo-5 

Do you still have this issue with the newest lib version?

**Comment by micdah** [comment] 2022-06-29 09:03
> @micdah @nemo-5
> 
> Do you still have this issue with the newest lib version?

Just took a look at the current version in `master` and from the looks of it, I would still expect to see the same issues as before.

A good example is combining this plugin with `chai-roughly` or similar, here is a demonstration I just threw together with that particular plugin:

```javascript
import {expect} from 'chai'

it('should equal in any order in combination with chai-roughly', function () {
    expect({
        values: [42.1, 0]
    }).to.roughly(0.1).deep.equalInAnyOrder({
        values: [0, 42.19]
    })
})
```

With the official version, this test fails.

Here's the version I am using locally instead

```javascript
    // Add deep-equal-in-any-order
    chai.use((chai, utils) => {
        const Assertion = chai.Assertion

        const sortDeep = (object) => {
            if (!Array.isArray(object)) {
                if (typeof object !== 'object' || object === null || object instanceof Date) {
                    return object;
                }

                return mapValues(object, sortDeep);
            }

            return sortAny(object.map(sortDeep));
        }

        /**
         * Asserts that <c>actual</c> value is equal (regardless of ordering of properties/members) to <c>value</c>
         * @namespace Chai
         * @name Assertion#equalInAnyOrder
         * @function
         * @param {*} value
         * @param {string} [m] Optional message
         * @returns Assertion
         */
        utils.addMethod(Assertion.prototype, 'equalInAnyOrder', function equalInAnyOrder(value, message) {
            // Sort actual value
            utils.flag(this, 'object', sortDeep(utils.flag(this, 'object')))

            // Assert (sorted) actual value is equal to (sorted) value
            this.equal(sortDeep(value), message)
        });

    })
```

Of course, this has the side effect of overwriting `object` by sorting it to chain in the `.equal(sortDeep(value), message)`, but one could probably also do a version where flags were copied over if we didn't want a side-effect on `object` on the existing assertion.

For my uses this works better, another good example would be `chai-exclude` which also can be useful in these kinds of sorting scenarios.

Honestly it's surprising to me these kinds of thing aren't chai native stuff, being able to compare disregarding ordering of members, doing approximate comparisons of numbers (_it's floating point numbero uno not to do `===` comparison here_) and likewise for excluding one or more members (_timestamps anyone? 🤣_)

**Comment by micdah** [comment] 2022-06-29 09:08
Oh `chai-roughly` might be a bad example, as it's broken right now, it uses a forked version of `deep_eql` which I think is no longer available so there are build issues.

I have made a fixed version of this also: https://github.com/Turbo87/chai-roughly/issues/8#issuecomment-793641060

Maybe I should put that on npmjs.com 🤔

**Comment by oprogramador** [comment] 2022-07-03 11:35
@micdah 

It's interesting that I cannot find `this.equal(` proposed by you in https://www.chaijs.com/plugins/chai-date-string/

**Comment by oprogramador** [comment] 2022-07-03 14:22
@micdah @nemo-5 

Could you check `deep-equal-in-any-order@2.0.0`?

**Comment by micdah** [comment] 2022-07-04 10:27
@oprogramador Excellent work, just tested `2.0.0` and it works beautifully now 👍 

I have subsequently removed my own version of this plugin from our codebase now and switched back to the offical version 🚀

**Comment by oprogramador** [comment] 2022-11-14 19:27
I close as it seems to be resolved.

If anything is still broken, please open a new issue with clear reproduction steps.

**Closed by oprogramador** 2022-11-14 19:27 UTC
